- name: This playbook will install,configure and deploys custom web page into ansible nodes
  hosts: all 
  tasks:
    - include: "install-nginx-{{ansible_distribution|lower}}.yml"
    - include: "configure-nginx-{{ansible_distribution|lower}}.yml"
    - include: common-nginx-tasks.yml
